Update flake8.yml

diff --git a/.github/workflows/flake8.yml b/.github/workflows/flake8.yml
--- a/.github/workflows/flake8.yml
+++ b/.github/workflows/flake8.yml
@@ -1,35 +1,21 @@
-name: Flake8 Code Quality Check
+name: flake8 Linting
 
-on:
-  pull_request:
-    branches:
-      - dev
-  push:
-    branches:
-      - dev
+on: [push, pull_request]
 
 jobs:
-  flake8:
+  lint:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
+      - uses: actions/checkout@v2
 
       - name: Set up Python
-        uses: actions/setup-python@v4
+        uses: actions/setup-python@v2
         with:
-          python-version: '3.10'
+          python-version: '3.x'
 
       - name: Install Flake8
         run: pip install flake8
 
       - name: Run Flake8
-        run: |
-          output=$(flake8 .)
-          if [ -n "$output" ]; then
-            echo "::error::Quality errors found. Cannot proceed."
-            echo "$output"
-            exit 1
-          else
-            echo "No quality errors found."
-          fi
+        id: flake8
+        run: flake8 . || echo "::error::Quality errors found. Cannot proceed." && exit 1
